### ISSUE TITLE
New Git Subcommands

### ISSUE THREAD

**Issue by iwoloschin** [zzamboni/elvish-completions#14]
New git (2.23.0) adds a few new subcommands, notable `git switch` (for, well, switching branches) and `git restore` (for restoring files).  They do not offer any new functionality, they just break up existing (and retained) functionality from `git checkout`.

This link probably explains it better than I can:
https://github.blog/2019-08-16-highlights-from-git-2-23/

**Comment by zzamboni** [comment]
@iwoloschin thanks for the pointer. I will take a look at this when I have some time. In the meantime, if you want to take a stab at it, this is  the part of the code that needs  to be updated: https://github.com/zzamboni/elvish-completions/blob/master/git.org#initialization-of-completion-definitions. The functions used in `git-completions` are defined shortly before.
