### ISSUE TITLE
Complete remote branch names on "git checkout"

### ISSUE THREAD

**Issue by uranusjr** [zzamboni/elvish-completions#18]
According to [git documentation on `checkout`](https://git-scm.com/docs/git-checkout#Documentation/git-checkout.txt-emgitcheckoutemltbranchgt):

>  If `<branch>` is not found but there does exist a tracking branch in exactly one remote (call it `<remote>`) with a matching name and `--no-guess` is not specified, treat as equivalent to
> ```
> $ git checkout -b <branch> --track <remote>/<branch>
> ```

So it may be worthwhile to complete branch names found in remotes in `checkout` (although probably too complicated to filter remote branches strictly according to the documented logic).

**Comment by zzamboni** [comment]
You can configure the `git checkout` completion to show all branches as follows:
```
use github.com/zzamboni/elvish-completions/git git-comp
git-comp:git-completions[checkout] = [ { git-comp:MODIFIED; git-comp:BRANCHES &all } ... ]
git-comp:init
```
Is this what you had in mind?

**Comment by zzamboni** [comment]
Closing this issue based on the comment above. Please reopen if needed.

**Comment by uranusjr** [comment]
Thanks for the tip. It’s not exactly what I want (the `$remote/` prefix shouldn’t be there), but I can write some custom code in the closure to do that myself.
