### ISSUE TITLE
Is it possible to use completions with a (shell) aliased git?

### ISSUE THREAD

**Issue by chipbuster** [zzamboni/elvish-completions#27]
I've [aliased](https://github.com/zzamboni/elvish-modules/blob/master/alias.org) `git` to `g` to more closely resemble a set of aliases I'm used to for git, but doing this seems to break autocompletion for all arguments. I tried to change `git-command`, but it appears that the value needs to resolve to an external command and can't be used with elvish functions.

Is there any way I can make use of completions while retaining this alias? Ideally I'd be able to have completions work with both `git` and `g`, but I'd be okay if they broke for `git`.

An example of what I'm attempting:

```
# in rc.elv
use github.com/zzamboni/elvish-modules/alias
use github.com/zzamboni/elvish-completions/git git-comp

alias:new g git

set git-comp:git-command = g
git-comp:init
```

This results in `Exception: exec: "g": executable file not found in $PATH`. I've tried a few simple things to try to get around this, but I'm not very experienced with Elvish and most of them wind up either with this or `variable <something> not found`.

Without the last two lines, things works fine with *git* aliases, e.g. I have `sta` aliased to `stash apply` in my `.gitconfig`. Autocompletion on `git sta` works fine, while autocompletion of `g stash apply` and `g sta` fall back to the file autocompleter.

**Comment by zzamboni** [comment]
To do this you have to assign the completion definition from `git` to your alias. For example:
```
set edit:completion:arg-completer[g] = $edit:completion:arg-completer[git]
```
After this, `g` should show the sample completions as `git`.

**Comment by chipbuster** [comment]
Thank you! Works like a charm.
