### ISSUE TITLE
Git autocompleter is not auto completing branch names

### ISSUE THREAD

**Issue by dcu** [zzamboni/elvish-completions#3]
am I missing something or it's not implemented yet?

**Comment by zzamboni** [comment]
This is implemented only for the `git checkout` command (the completer also understands `git co`, which is an alias I use for `checkout`).

For which other commands do you need it? It's probably not too hard to add it.

**Comment by dcu** [comment]
`git merge`, `git rebase`, `git push` and `git branch`/`git br` are a must in my workflow. `git pull` would be nice to have

**Comment by dcu** [comment]
`git merge` and `git branch`/

**Comment by zzamboni** [comment]
Fixed by 31331f120d42da45ccf9de622593d3b9a17c4e5b and 6630c5c25b5ab5ceb3b77684b5507df2644b5077.

I'm not sure that completing existing branches is appropriate for `git branch`, what did you have in mind?
