### ISSUE TITLE
Automatically extract git long  options from man pages

### ISSUE THREAD

**Issue by notramo** [zzamboni/elvish-completions#4]
It can be done with similar solution:
```elvish
man git-pull | rg -o -- '--\w+' | sort -u
```

**Comment by zzamboni** [comment]
Good idea, I'm working on it, but just want to post this here because it is so cool. Using only Elvish and "index distribution":
```
put (man git-pull | each [l]{ re:find '(--\w+)' $l })[groups][1][text]
```

**Comment by zzamboni** [comment]
This is implemented in the latest version of git.elv.
